In [1]:
!pip install espn_api

Requirement already satisfied: espn_api in /opt/anaconda3/lib/python3.9/site-packages (0.45.1)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /opt/anaconda3/lib/python3.9/site-packages (from espn_api) (2.31.0)
Requirement already satisfied: urllib3<=2.2.3 in /opt/anaconda3/lib/python3.9/site-packages (from espn_api) (1.26.18)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.9/site-packages (from requests<3.0.0,>=2.0.0->espn_api) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.9/site-packages (from requests<3.0.0,>=2.0.0->espn_api) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.9/site-packages (from requests<3.0.0,>=2.0.0->espn_api) (2021.10.8)

[notice] A new release of pip is available: 24.1.2 -> 25.3
[notice] To update, run: pip install --upgrade pip

In [2]:
from espn_api.football import League
import pandas as pd
import numpy as np
import sqlite3

pd.set_option('display.max_columns', None)

In [3]:
LEAGUE_ID = 86952922
espn_s2 = "AEC20e998honXS4Wi0Z8qzlJdam4%2F%2BaApa7apspnhKR0Npb%2FMsF5DuQsFUcHW%2FhPihQun9U6PGITOi2CkbdfDCkUc8druBVhAwT08Lzrvv8oZli8YAuTi9mIWg7YqtorCNOEKPxHpYswnT3q7b885tRDKBJpLCH0T2h4h1p%2B02SfdlDhjEB2gHqFk1xl6tJRNMBiCkZ8i5RttLW6ER9ZvLTmmAdb5ceZhQ27NEMiMf%2BjWSSvwBdnf2roxwt9baw33BVnnITqYVb8FXsaUwm7%2Bm0m9GLQ%2B66%2BU%2Brg%2BQngXm1ekA%3D%3D"
swid = "{B431504E-F779-4C49-B3E8-28DDF7409957}"

def get_league(year):
    league = League(league_id=LEAGUE_ID, year=year, swid=swid, espn_s2=espn_s2)
    return league

In [4]:
def query(query):
    conn = sqlite3.connect('weekly_fantasy_data.db')
    return pd.read_sql_query(query, conn)

In [5]:
league = get_league(2025)

In [10]:
query('select * from z_scores where player_name = "Marvin Harrison Jr."')

,id,league_id,player_name,fantasy_pos,week,weekly_points_ppr,log_ppr,z_week_ppr,year,fantasy_team,created_at
0,29167,86952922,Marvin Harrison Jr.,WR,17,15.6,1.193125,0.641831,2024,None,2025-12-04 23:27:55
1,29371,86952922,Marvin Harrison Jr.,WR,16,7.9,0.897627,-0.211655,2024,None,2025-12-04 23:27:55
2,29584,86952922,Marvin Harrison Jr.,WR,15,5.2,0.716003,-0.736239,2024,None,2025-12-04 23:27:55
3,29790,86952922,Marvin Harrison Jr.,WR,14,8.9,0.949390,-0.062148,2024,None,2025-12-04 23:27:55
4,29978,86952922,Marvin Harrison Jr.,WR,13,17.0,1.230449,0.749634,2024,None,2025-12-04 23:27:55
5,30189,86952922,Marvin Harrison Jr.,WR,12,7.7,0.886491,-0.243820,2024,None,2025-12-04 23:27:55
6,30592,86952922,Marvin Harrison Jr.,WR,10,16.4,1.214844,0.704562,2024,None,2025-12-04 23:27:55
7,30792,86952922,Marvin Harrison Jr.,WR,9,3.4,0.531479,-1.269201,2024,None,2025-12-04 23:27:55
8,31004,86952922,Marvin Harrison Jr.,WR,8,23.1,1.363612,1.134249,2024,None,2025-12-04 23:27:55
9,31223,86952922,Marvin Harrison Jr.,WR,7,5.1,0.707570,-0.760596,2024,None,2025-12-04 23:27:55
10,31624,86952922,Marvin Harrison Jr.,WR,5,5.6,0.748188,-0.643280,2024,None,2025-12-04 23:27:55
11,31835,86952922,Marvin Harrison Jr.,WR,4,15.5,1.190332,0.633764,2024,None,2025-12-04 23:27:55
12,32062,86952922,Marvin Harrison Jr.,WR,3,17.4,1.240549,0.778807,2024,None,2025-12-04 23:27:55
13,32291,86952922,Marvin Harrison Jr.,WR,2,29.0,1.462398,1.419573,2024,None,2025-12-04 23:27:55
14,32529,86952922,Marvin Harrison Jr.,WR,1,1.4,0.146128,-2.382210,2024,None,2025-12-04 23:27:55
15,32765,86952922,Marvin Harrison Jr.,WR,11,0.0,0.000000,0.000000,2024,None,2025-12-04 23:27:55
16,33025,86952922,Marvin Harrison Jr.,WR,2,4.7,0.672098,-0.875263,2025,None,2025-12-04 23:31:59
17,33266,86952922,Marvin Harrison Jr.,WR,1,18.1,1.257679,0.912263,2025,None,2025-12-04 23:31:59
18,33903,86952922,Marvin Harrison Jr.,WR,10,14.3,1.155336,0.599855,2025,None,2025-12-04 23:31:59
19,34108,86952922,Marvin Harrison Jr.,WR,9,22.6,1.354108,1.206622,2025,None,2025-12-04 23:31:59
20,34496,86952922,Marvin Harrison Jr.,WR,7,7.8,0.892095,-0.203708,2025,None,2025-12-04 23:31:59
21,34709,86952922,Marvin Harrison Jr.,WR,6,5.2,0.716003,-0.741238,2025,None,2025-12-04 23:31:59
22,34912,86952922,Marvin Harrison Jr.,WR,5,13.8,1.139879,0.552672,2025,None,2025-12-04 23:31:59
23,35125,86952922,Marvin Harrison Jr.,WR,4,18.6,1.269513,0.948388,2025,None,2025-12-04 23:31:59
24,35361,86952922,Marvin Harrison Jr.,WR,3,7.4,0.869232,-0.273498,2025,None,2025-12-04 23:31:59
25,35533,86952922,Marvin Harrison Jr.,WR,8,0.0,0.000000,0.000000,2025,None,2025-12-04 23:31:59

In [35]:
league.recent_activity(size=5)

[Activity((Team(Beafy keefey),DROPPED,Player(Chuba Hubbard)) (Team(Beafy keefey),FA ADDED,Player(Theo Johnson))),
 Activity((Team(Team E Brenner),DROPPED,Player(Jordan Love))),
 Activity((Team(The Reptilians ),WAIVER ADDED,Player(Ka'imi Fairbairn)) (Team(The Reptilians ),DROPPED,Player(Jake Elliott))),
 Activity((Team(Joshin' Aroun'),DROPPED,Player(Josh Downs)) (Team(Joshin' Aroun'),FA ADDED,Player(Rashid Shaheed))),
 Activity((Team(Buck Chair),DROPPED,Player(Jared Goff)))]

In [29]:
%pip install nfl-data-py

Requirement already satisfied: nfl-data-py in /opt/anaconda3/lib/python3.9/site-packages (0.3.0)
Requirement already satisfied: pandas>1 in /opt/anaconda3/lib/python3.9/site-packages (from nfl-data-py) (1.5.2)
Requirement already satisfied: appdirs>1 in /opt/anaconda3/lib/python3.9/site-packages (from nfl-data-py) (1.4.4)
Requirement already satisfied: fastparquet>0.5 in /opt/anaconda3/lib/python3.9/site-packages (from nfl-data-py) (2022.12.0)
Requirement already satisfied: python-snappy>0.5 in /opt/anaconda3/lib/python3.9/site-packages (from nfl-data-py) (0.6.0)
Requirement already satisfied: numpy>=1.20.3 in /opt/anaconda3/lib/python3.9/site-packages (from fastparquet>0.5->nfl-data-py) (1.22.4)
Requirement already satisfied: cramjam>=2.3 in /opt/anaconda3/lib/python3.9/site-packages (from fastparquet>0.5->nfl-data-py) (2.6.2)
Requirement already satisfied: fsspec in /opt/anaconda3/lib/python3.9/site-packages (from fastparquet>0.5->nfl-data-py) (2025.3.2)
Requirement already satisfied: packaging in /Users/arjun/.local/lib/python3.9/site-packages (from fastparquet>0.5->nfl-data-py) (24.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/arjun/.local/lib/python3.9/site-packages (from pandas>1->nfl-data-py) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.9/site-packages (from pandas>1->nfl-data-py) (2023.3)
Requirement already satisfied: six>=1.5 in /Users/arjun/.local/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas>1->nfl-data-py) (1.17.0)

[notice] A new release of pip is available: 24.1.2 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import nfl_data_py as nfl

NameError: name 'league' is not defined

In [9]:
nfl.import_team_desc()

,team_abbr,team_name,team_id,team_nick,team_conf,team_division,team_color,team_color2,team_color3,team_color4,team_logo_wikipedia,team_logo_espn,team_wordmark,team_conference_logo,team_league_logo,team_logo_squared
0,ARI,Arizona Cardinals,3800,Cardinals,NFC,NFC West,#97233F,#000000,#ffb612,#a5acaf,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/ari.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
1,ATL,Atlanta Falcons,200,Falcons,NFC,NFC South,#A71930,#000000,#a5acaf,#a30d2d,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/atl.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
2,BAL,Baltimore Ravens,325,Ravens,AFC,AFC North,#241773,#9E7C0C,#9e7c0c,#c60c30,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/bal.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
3,BUF,Buffalo Bills,610,Bills,AFC,AFC East,#00338D,#C60C30,#0c2e82,#d50a0a,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/buf.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
4,CAR,Carolina Panthers,750,Panthers,NFC,NFC South,#0085CA,#000000,#bfc0bf,#0085ca,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500-dark...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
5,CHI,Chicago Bears,810,Bears,NFC,NFC North,#0B162A,#E64100,#0b162a,#E64100,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/chi.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
6,CIN,Cincinnati Bengals,920,Bengals,AFC,AFC North,#FB4F14,#000000,#000000,#d32f1e,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/cin.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
7,CLE,Cleveland Browns,1050,Browns,AFC,AFC North,#FF3C00,#311D00,#a5acaf,#d32f1e,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/cle.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
8,DAL,Dallas Cowboys,1200,Cowboys,NFC,NFC East,#002244,#B0B7BC,#acc0c6,#a5acaf,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/dal.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
9,DEN,Denver Broncos,1400,Broncos,AFC,AFC West,#002244,#FB4F14,#00234c,#ff5200,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/den.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
10,DET,Detroit Lions,1540,Lions,NFC,NFC North,#0076B6,#B0B7BC,#000000,#004e89,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/det.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
11,GB,Green Bay Packers,1800,Packers,NFC,NFC North,#203731,#FFB612,#1c2d25,#eead1e,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/gb.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
12,HOU,Houston Texans,2120,Texans,AFC,AFC South,#03202F,#A71930,#00071c,#a30d2d,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/hou.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
13,IND,Indianapolis Colts,2200,Colts,AFC,AFC South,#002C5F,#a5acaf,#013369,#9ba1a2,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/ind.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
14,JAX,Jacksonville Jaguars,2250,Jaguars,AFC,AFC South,#006778,#000000,#9f792c,#d7a22a,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/jax.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
15,KC,Kansas City Chiefs,2310,Chiefs,AFC,AFC West,#E31837,#FFB612,#000000,#e31837,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/kc.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
16,LA,Los Angeles Rams,2510,Rams,NFC,NFC West,#003594,#FFD100,#001532,#af925d,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/lar.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
17,LAC,Los Angeles Chargers,4400,Chargers,AFC,AFC West,#007BC7,#ffc20e,#ffb612,#001532,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/lac.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
18,LAR,Los Angeles Rams,2510,Rams,NFC,NFC West,#003594,#FFD100,#001532,#af925d,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/lar.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
19,LV,Las Vegas Raiders,2520,Raiders,AFC,AFC West,#000000,#A5ACAF,#a6aeb0,#000000,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/lv.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
20,MIA,Miami Dolphins,2700,Dolphins,AFC,AFC East,#008E97,#F58220,#005778,#008e97,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/mia.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
21,MIN,Minnesota Vikings,3000,Vikings,NFC,NFC North,#4F2683,#FFC62F,#e9bf9b,#000000,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/min.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
22,NE,New England Patriots,3200,Patriots,AFC,AFC East,#002244,#C60C30,#b0b7bc,#001532,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/ne.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
23,NO,New Orleans Saints,3300,Saints,NFC,NFC South,#D3BC8D,#000000,#9f8958,#000000,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/no.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
24,NYG,New York Giants,3410,Giants,NFC,NFC East,#0B2265,#A71930,#a5acaf,#012352,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
25,NYJ,New York Jets,3430,Jets,AFC,AFC East,#003F2D,#000000,NaN,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
26,OAK,Oakland Raiders,2520,Raiders,AFC,AFC West,#000000,#A5ACAF,#a6aeb0,#000000,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/lv.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
27,PHI,Philadelphia Eagles,3700,Eagles,NFC,NFC East,#004C54,#A5ACAF,#acc0c6,#000000,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/phi.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
28,PIT,Pittsburgh Steelers,3900,Steelers,AFC,AFC North,#000000,#FFB612,#c60c30,#00539b,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/pit.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
29,SD,San Diego Chargers,4400,Chargers,AFC,AFC West,#007BC7,#ffc20e,#ffb612,#001532,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/lac.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
30,SEA,Seattle Seahawks,4600,Seahawks,NFC,NFC West,#002244,#69be28,#a5acaf,#001532,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/sea.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
31,SF,San Francisco 49ers,4500,49ers,NFC,NFC West,#AA0000,#B3995D,#000000,#a5acaf,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/sf.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
32,STL,St. Louis Rams,2510,Rams,NFC,NFC West,#003594,#FFD100,#001532,#af925d,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/lar.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
33,TB,Tampa Bay Buccaneers,4900,Buccaneers,NFC,NFC South,#A71930,#322F2B,#000000,#ff7900,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/tb.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
34,TEN,Tennessee Titans,2100,Titans,AFC,AFC South,#002244,#4B92DB,#c60c30,#a5acaf,https://github.com/nflverse/nflverse-pbp/raw/m...,https://a.espncdn.com/i/teamlogos/nfl/500/ten.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
35,WAS,Washington Commanders,5110,Commanders,NFC,NFC East,#5A1414,#FFB612,#000000,#5b2b2f,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...

In [5]:
nfl.import_players().headshot

0        https://static.www.nfl.com/image/private/f_aut...
1        https://static.www.nfl.com/image/upload/f_auto...
2        https://static.www.nfl.com/image/private/f_aut...
3        https://static.www.nfl.com/image/private/f_aut...
4        https://static.www.nfl.com/image/private/f_aut...
                               ...
24331    https://static.www.nfl.com/image/private/f_aut...
24332    https://static.www.nfl.com/image/private/f_aut...
24333    https://static.www.nfl.com/image/private/f_aut...
24334    https://static.www.nfl.com/image/private/f_aut...
24335    https://static.www.nfl.com/image/private/f_aut...
Name: headshot, Length: 24336, dtype: object

In [79]:
query("select * from z_scores where player_name = 'Ashton Jeanty'")

,id,year,player_name,fantasy_pos,week,weekly_points_ppr,log_ppr,z_week_ppr,fantasy_team,created_at,starter
0,None,2025,Ashton Jeanty,RB,2,7.4,0.869232,0.018914,RAWDOGS ®,None,None
1,None,2025,Ashton Jeanty,RB,1,12.0,1.079181,0.480457,RAWDOGS ®,None,None
2,None,2025,Ashton Jeanty,RB,12,24.8,1.394452,1.173532,Deeeej,None,None
3,None,2025,Ashton Jeanty,RB,11,9.4,0.973128,0.247314,Brxggzy Bunch,None,None
4,None,2025,Ashton Jeanty,RB,10,15.3,1.184691,0.712405,Brxggzy Bunch,None,None
5,None,2025,Ashton Jeanty,RB,9,19.9,1.298853,0.963373,Brxggzy Bunch,None,None
6,None,2025,Ashton Jeanty,RB,7,4.4,0.643453,-0.477428,Brxggzy Bunch,None,None
7,None,2025,Ashton Jeanty,RB,6,16.6,1.220108,0.790264,Brxggzy Bunch,None,None
8,None,2025,Ashton Jeanty,RB,5,15.9,1.201397,0.749130,Brxggzy Bunch,None,None
9,None,2025,Ashton Jeanty,RB,4,33.5,1.525045,1.460622,Brxggzy Bunch,None,None
10,None,2025,Ashton Jeanty,RB,3,6.3,0.799341,-0.134732,RAWDOGS ®,None,None

In [90]:
query("select * from z_scores where player_name = 'Alvin Kamara' and year = 2025")

,id,year,player_name,fantasy_pos,week,weekly_points_ppr,log_ppr,z_week_ppr,fantasy_team,created_at,starter
0,None,2025,Alvin Kamara,RB,2,16.0,1.204120,0.755116,Buck Chair,None,None
1,None,2025,Alvin Kamara,RB,1,13.7,1.136721,0.606948,Buck Chair,None,None
2,None,2025,Alvin Kamara,RB,12,3.5,0.544068,-0.695911,Faid XE,None,None
3,None,2025,Alvin Kamara,RB,10,14.5,1.161368,0.661132,Faid XE,None,None
4,None,2025,Alvin Kamara,RB,9,0.7,-0.154902,-2.232494,Faid XE,None,None
5,None,2025,Alvin Kamara,RB,8,6.5,0.812913,-0.104894,Faid XE,None,None
6,None,2025,Alvin Kamara,RB,7,5.9,0.770852,-0.197360,Faid XE,None,None
7,None,2025,Alvin Kamara,RB,6,12.6,1.100371,0.527038,Faid XE,None,None
8,None,2025,Alvin Kamara,RB,5,9.5,0.977724,0.257417,Faid XE,None,None
9,None,2025,Alvin Kamara,RB,4,11.2,1.049218,0.414587,Faid XE,None,None
10,None,2025,Alvin Kamara,RB,3,6.6,0.819544,-0.090318,Faid XE,None,None

In [94]:
query("""
      with trades as (select * from player_trades_2025)
      
      select z_scores.player_name, trades.trade_id, 
      trades.to_team_name, sum(weekly_points_ppr) as total_points_ppr, 
      count(distinct z_scores.week) as n,
      sum(z_week_ppr) as total_z
      from z_scores join trades 
      on trades.player_name = z_scores.player_name AND trades.to_team_name = z_scores.fantasy_team 
      where z_scores.year = 2025 and z_scores.week > trades.week
      group by z_scores.player_name, trades.trade_id, trades.to_team_name order by trade_id
      
      
      """)

           player_name trade_id   to_team_name  total_points_ppr  n   total_z
0        Jaylen Warren    3_3_5         Deeeej             86.90  7  3.253051
1   Kenneth Walker III    3_3_5           Herb             82.20  8  1.978761
2          Tee Higgins    3_3_5           Herb            118.10  8  3.652404
3         Alvin Kamara    3_6_9        Faid XE             64.40  8 -1.370484
4          Jerry Jeudy    3_6_9        Faid XE             49.20  6 -2.463242
5           Puka Nacua    3_6_9     Buck Chair            136.50  7  5.713603
6        Ashton Jeanty    4_1_7  Brxggzy Bunch             81.50  6  2.985057
7         Cam Skattebo    4_1_7      RAWDOGS ®             73.80  4  3.236039
8   Jaxon Smith-Njigba    4_1_7  Brxggzy Bunch            183.70  7  9.596204
9          Rome Odunze    4_1_7      RAWDOGS ®             63.70  6 -0.222984
10         David Njoku   4_2_14  Ookie Cookies             50.00  5 -0.097282
11    Jameson Williams   4_2_14  Ookie Cookies              2.00  1 -2.033301
12        Brock Bowers    4_5_9     Buck Chair             72.70  4  2.577979
13       Jake Ferguson    4_5_9         Deeeej             88.80  6  4.447690
14    Javonte Williams    4_5_9         Deeeej            101.70  7  3.991308
15        Vikings D/ST    4_5_9         Deeeej              3.00  1 -0.891413
16         Breece Hall   4_6_10        Faid XE             17.50  1  0.840672
17         Romeo Doubs   4_6_10      Team Jeev             64.30  7 -1.973596
18         Breece Hall   6_6_14  Ookie Cookies             83.86  5  3.196070
19         CeeDee Lamb   6_6_14        Faid XE             69.70  4  3.346223
20         Cooper Kupp   6_6_14  Ookie Cookies             21.30  4 -3.591302
21    Jameson Williams   6_6_14        Faid XE             60.20  3  3.080820
22  TreVeyon Henderson   9_9_14     Buck Chair             71.40  3  3.121219